### ISSUE TITLE
[0.5pt] Add header - group task

### ISSUE THREAD

**Issue by gealsanchez** [gealsanchez/capstoneJavaScript#17]
Create page header according to the wireframe:

<img width="541" alt="Screenshot 2021-06-27 at 21 42 24" src="https://user-images.githubusercontent.com/7466903/123557332-ac3eee80-d790-11eb-91c8-9f8a6a38a4ff.png">

**Comment by gealsanchez** [comment]
### Hi @anderCM ,  

You have done an incredible job 👏🏾👏🏾👏🏾  
However, there are still some changes that aren't addressed yet. You are almost there! 💪🏾 

## Required Changes ♻️

**Please fix the counter of meals in the header because is not showing the count, thanks**

Cheers 🥂  and Happy coding!!! 👯 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @gealsanchez in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by anderCM** [comment]
Hi @gealsanchez .
I have updated it [here](https://github.com/gealsanchez/capstoneJavaScript/blob/285c7cdd84afbc37e2efe95c64a6d6e2855e5bb1/src/index.html#L21)
