### ISSUE TITLE
[0.5pt] Find external API - group task

### ISSUE THREAD

**Issue by gealsanchez** [gealsanchez/capstoneJavaScript#20]
Find an API to base the development of the webapp around it. The API should allow you to
  - Get a list of items with a unique item id (or generate the unique id).
  - For a given item, get detailed information about it.
choose an APIs that doesn't need authentication. if you select an API that requires authentication, you should implement it on your own. Also, if you select an API that provides image resources your webapp will be more visual.

**Comment by anderCM** [comment]
# Hi @gealsanchez ,
You have done an incredible job.  😉

Status: Approved ✔
There is nothing else to say other than... it's time to merge it!


# Highlights.
- Clean code structure.
- No linterns error

If you have any question about my review, please feel free to leave a comment. **Dont forget to tag me @anderCM  to notify me**
