### ISSUE TITLE
Set up Kanban board

### ISSUE THREAD

**Issue by gealsanchez** [gealsanchez/capstoneJavaScript#21]
**Team Members:**

1. @gealsanchez 
2. @anderCM 

Here you can see the link to our [Kanban board](https://github.com/users/gealsanchez/projects/1/views/1)

**Comment by MahmoudBakr23** [comment]
Hi team😃, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit:
Congratulations! 🎉 

**Highlights**
- Well done on dividing the tasks between the two of you

Cheers and Happy coding!👏👏👏

Feel free to mention @MahmoudBakr23 to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
